version: '3.8'

services:
  gotify_server:
    container_name: "gotify_server"
    image: gotify/server
    volumes:
      - ./gotify/data:/app/data
    environment:
      GOTIFY_SERVER_CORS_ALLOWMETHODS: "- \"GET\"\n- \"POST\"\n- \"OPTIONS\"\n- \"DELETE\""
      GOTIFY_SERVER_CORS_ALLOWORIGINS: "- \".*\""
      GOTIFY_SERVER_CORS_ALLOWHEADERS: "- \"Authorization\"\n- \"content-type\""
      GOTIFY_SERVER_STREAM_ALLOWEDORIGINS: "- \".*\""
    ports:
      - 8000:80
  ng_cli:
    container_name: "ng_cli"
    image: trion/ng-cli
    command: sh -c "[ -d \"node_modules\" ] || npm install && ng build --watch"
    volumes:
      - ..:/app
